defmodule CovidtrackingDotComApi.State do
  alias CovidtrackingDotComApi.Utils.Builder

  @states [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY"
  ]
  defstruct state: nil,
            positive: -1,
            negative: -1,
            totalTestResults: -1,
            hospitalizedCumulative: -1,
            hospitalizedCurrently: -1,
            inIcuCurrently: -1,
            inIcuCumulative: -1,
            onVentilatorCurrently: -1,
            onVentilatorCumulative: -1,
            commercialScore: -1,
            dateChecked: nil,
            dateModified: nil,
            grade: nil,
            negativeRegularScore: -1,
            negativeScore: -1,
            positiveScore: -1,
            score: -1,
            death: -1,
            hash: nil,
            notes: nil

  def get(state) when state in @states do
    Builder.single(__MODULE__, "states", "state=#{state}")
  end
end
